# frozen_string_literal: true

# The CSV and SQLite writers, their gzip, and the cross-format validator
# (PRD ids S01-S07 and C01-C04).
#
# Every expectation here is hand-authored: the CSV lines are typed out as
# text, the IPv6 renderings come from RFC 5952 read by a human, and the
# SQLite probes assert values chosen before the writer ran. Nothing is
# generated by calling the code under test, because a test that asks the
# writer what it wrote only proves the writer is consistent with itself.
#
# The SQLite cases drive real SQLite through the resolved interpreter (a
# throwaway script per case, so sqlite.py's CLI stays exactly the two modes
# the PRD defines). Where Ruby is known correct - IPAddr PARSES fine even
# where it FORMATS wrong - it is used as the independent oracle.

require_relative "test_helper"
require "json"
require "open3"
require "zlib"
require_relative "../pipeline/export/contract"
require_relative "../pipeline/export/csv"
require_relative "../pipeline/export/gzip"
require_relative "../pipeline/export/metadata"
require_relative "../pipeline/export/sqlite"
require_relative "../pipeline/export/validate"

module OpenASNPipeline
  class ExportWritersTest < Minitest::Test
    Csv      = Export::Csv
    Contract = Export::Contract

    # A payload with every flag false and no ASN evidence, so a case only
    # has to state what it is actually about.
    BLANK = {
      "asn" => nil, "as_org" => nil, "category" => nil, "network_role" => nil,
      "bad_asn" => false, "vpn_provider" => false, "mobile_carrier" => false,
      "enterprise_gw" => false, "cdn" => false, "hosting_extra" => false,
      "vpn_range" => false, "datacenter_range" => false,
      "core_verdict" => "unknown", "core_sources" => ["unrouted"]
    }.freeze

    ISP = {
      "asn" => 100, "as_org" => "Access A", "category" => "isp", "network_role" => "access_provider",
      "core_verdict" => "residential_isp", "core_sources" => ["asn_category"]
    }.freeze

    def setup
      @dir = File.join(WORK_DIR, "test-#{name}")
      FileUtils.mkdir_p(@dir)
    end

    def teardown
      FileUtils.rm_rf(@dir)
    end

    # --- IPv6 text: the R1 defect this formatter exists to avoid ---------

    def test_the_mapped_prefix_is_written_as_pure_hextets_not_a_dotted_quad
      # IPAddr#to_s renders this as "::ffff:8.8.8.8" (measured, ruby 3.4.2),
      # which PRD §11 forbids. The CSV must not inherit that.
      mapped = 0x0000_0000_0000_0000_0000_ffff_0808_0808
      assert_equal "::ffff:808:808", Csv.v6_text(mapped)
      assert_equal "::ffff:0:0", Csv.v6_text(0x0000_0000_0000_0000_0000_ffff_0000_0000)
      refute_includes Csv.v6_text(mapped), "."
    end

    def test_a_tie_between_equal_zero_runs_compresses_the_leftmost_one
      # 1:0:0:2:0:0:3:4 has two runs of two; RFC 5952 §4.2.3 takes the first.
      assert_equal "1::2:0:0:3:4", Csv.v6_text(0x0001_0000_0000_0002_0000_0000_0003_0004)
    end

    def test_a_longer_run_wins_over_an_earlier_shorter_one
      assert_equal "2001:0:0:1::1", Csv.v6_text(0x2001_0000_0000_0001_0000_0000_0000_0001)
    end

    def test_a_single_zero_hextet_is_never_compressed
      assert_equal "0:1:0:1:0:1:0:1", Csv.v6_text(0x0000_0001_0000_0001_0000_0001_0000_0001)
      assert_equal "1:2:3:4:5:6:7:0", Csv.v6_text(0x0001_0002_0003_0004_0005_0006_0007_0000)
    end

    def test_the_all_zero_address_and_the_maximum_address
      assert_equal "::", Csv.v6_text(0)
      assert_equal "ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff", Csv.v6_text(Contract::ADDRESS_MAX[:ipv6])
      assert_equal "::1", Csv.v6_text(1)
    end

    def test_the_formatter_agrees_with_ruby_where_ruby_is_known_correct
      # Everything outside ::ffff:0:0/96; these are the cases R1 measured as
      # correct in IPAddr, so agreeing with it is real evidence.
      [0x2001_0db8_0000_0000_0000_0000_0000_0001,
       0x2001_0000_0000_0001_0000_0000_0000_0001,
       0x0001_0000_0000_0002_0000_0000_0003_0004,
       0x0000_0001_0000_0001_0000_0001_0000_0001,
       0xfe80_0000_0000_0000_0202_b3ff_fe1e_8329,
       0, 1, Contract::ADDRESS_MAX[:ipv6]].each do |value|
        assert_equal IPAddr.new(value, Socket::AF_INET6).to_s, Csv.v6_text(value), "for #{value}"
      end
    end

    def test_ipv4_text_has_no_leading_zeros_and_covers_both_bounds
      assert_equal "0.0.0.0", Csv.v4_text(0)
      assert_equal "1.2.3.4", Csv.v4_text(0x01020304)
      assert_equal "10.0.0.1", Csv.v4_text(0x0a000001)
      assert_equal "255.255.255.255", Csv.v4_text(Contract::ADDRESS_MAX[:ipv4])
    end

    # --- C01 ------------------------------------------------------------

    def test_the_header_and_every_cell_encoding_are_written_verbatim
      path = write_csv([
        record(4, "01000000", "01000004", ISP),
        record(4, "0a000000", "0a0000ff", BLANK.merge("vpn_range" => true, "core_verdict" => "vpn",
                                                      "core_sources" => %w[x4b_vpn])),
        record(6, "20010db8000000000000000000000000",
               "20010db80000000000000000ffffffff",
               { "asn" => 0, "as_org" => "Zero AS", "category" => "hosting",
                 "network_role" => "content_network", "cdn" => true,
                 "core_verdict" => "hosting", "core_sources" => %w[asn_cdn asn_category] })
      ])

      assert_equal <<~CSV, File.read(path)
        ip_version,start_ip,end_ip,asn,as_org,category,network_role,bad_asn,vpn_provider,mobile_carrier,enterprise_gw,cdn,hosting_extra,vpn_range,datacenter_range,core_verdict,core_sources
        4,1.0.0.0,1.0.0.4,100,Access A,isp,access_provider,0,0,0,0,0,0,0,0,residential_isp,asn_category
        4,10.0.0.0,10.0.0.255,,,,,0,0,0,0,0,0,1,0,vpn,x4b_vpn
        6,2001:db8::,2001:db8::ffff:ffff,0,Zero AS,hosting,content_network,0,0,0,0,1,0,0,0,hosting,asn_cdn|asn_category
      CSV
    end

    def test_the_header_is_the_contract_header_and_the_file_has_no_bom
      path = write_csv([record(4, "01000000", "01000000", ISP)])
      bytes = File.binread(path)

      refute bytes.start_with?("\xEF\xBB\xBF".b), "a BOM would break every naive parser"
      assert_equal Contract::CSV_HEADER, bytes.lines.first.chomp("\n")
      assert bytes.end_with?("\n"), "every record is LF-terminated"
      refute_includes bytes, "\r\n"
    end

    def test_a_parser_round_trip_returns_exactly_the_spool_values
      records = [
        record(4, "01000000", "01000004", ISP),
        record(4, "7fffffff", "80000000", BLANK.merge("asn" => 4294967295, "as_org" => "Max AS")),
        record(6, "00000000000000000000ffff08080808", "00000000000000000000ffff08080808", ISP)
      ]
      path = write_csv(records)

      parsed = ::CSV.read(path, headers: true)
      assert_equal 3, parsed.length
      parsed.each_with_index do |row, index|
        want = records[index]
        assert_equal want["ip_version"], Integer(row["ip_version"])
        assert_equal IPAddr.new(Integer(want["start_hex"], 16),
                                want["ip_version"] == 4 ? Socket::AF_INET : Socket::AF_INET6).to_i,
                     IPAddr.new(row["start_ip"]).to_i
        assert_equal want["as_org"], row["as_org"]
        assert_equal want["core_sources"], row["core_sources"].split("|")
        Contract::SIGNALS.each { |s| assert_equal(want[s.to_s] ? "1" : "0", row[s.to_s], s.to_s) }
      end
      assert_nil parsed[1]["category"], "a null category is an empty cell, read back as nil"
    end

    # --- C02 ------------------------------------------------------------

    def test_ipv6_endpoints_reach_the_csv_in_canonical_form
      path = write_csv([
        record(6, "00000000000000000000000000000000", "00000000000000000000000000000001", BLANK),
        record(6, "00010000000000020000000000030004", "20010000000000010000000000000001", BLANK)
      ])
      lines = File.readlines(path).drop(1)

      assert lines[0].start_with?("6,::,::1,"), lines[0]
      assert lines[1].start_with?("6,1::2:0:0:3:4,2001:0:0:1::1,"), lines[1]
    end

    # --- C03 ------------------------------------------------------------

    def test_an_org_name_with_a_comma_a_quote_and_a_newline_survives_exactly
      org = %(Acme, "The" Best\nISP)
      path = write_csv([record(4, "01000000", "01000004", ISP.merge("as_org" => org)),
                        record(4, "02000000", "02000004", ISP)])

      text = File.read(path)
      assert_includes text, %("Acme, ""The"" Best\nISP")

      physical = File.readlines(path).length
      logical = ::CSV.read(path, headers: true)
      assert_equal 4, physical, "header + 2 records, one of which spans two physical lines"
      assert_equal 2, logical.length
      assert_equal org, logical[0]["as_org"], "exact bytes, including the embedded newline"

      # And the writer's own count is the LOGICAL one, which is the number
      # that reaches the manifest.
      result = Csv.write(File.join(@dir, "records.jsonl"), path: File.join(@dir, "again.csv"))
      assert_equal 2, result.total
      assert_equal 2, result.ipv4
    end

    # --- C04 ------------------------------------------------------------

    def test_identical_inputs_produce_identical_gzip_bytes
      records = [record(4, "01000000", "01000004", ISP), record(6, "20010db8" + "0" * 24, "20010db8" + "f" * 24, BLANK)]
      first = write_csv(records, name: "one.csv")
      second = write_csv(records, name: "two.csv")
      assert_equal Digest::SHA256.file(first).hexdigest, Digest::SHA256.file(second).hexdigest

      a = Export::Gzip.compress(first, output: File.join(@dir, "one.csv.gz"))
      b = Export::Gzip.compress(second, output: File.join(@dir, "two.csv.gz"))
      assert_equal a.sha256, b.sha256
      assert_equal a.bytes, b.bytes
    end

    def test_the_gzip_header_carries_no_timestamp_and_no_filename
      path = write_csv([record(4, "01000000", "01000004", ISP)])
      gz = Export::Gzip.compress(path, output: File.join(@dir, "openasn.csv.gz"))
      header = File.binread(gz.path, 10)

      # 1f8b magic, 08 deflate, 00 flags (no FNAME/FCOMMENT), 00000000 mtime.
      assert_equal "1f8b0800000000000003", header.unpack1("H*")
      assert_equal File.read(path), Zlib::GzipReader.open(gz.path, &:read)
    end

    # --- S01, S02, S04, S05: real SQLite through the real query ---------

    def test_ipv4_addresses_above_the_signed_boundary_store_and_query_intact
      db = build_database([
        record(4, "7ffffffe", "7fffffff", ISP.merge("asn" => 1)),
        record(4, "80000000", "80000001", ISP.merge("asn" => 2)),
        record(4, "fffffffe", "ffffffff", ISP.merge("asn" => 3))
      ])

      assert_equal [0x7ffffffe, 1], lookup_v4(db, 0x7fffffff)
      assert_equal [0x80000000, 2], lookup_v4(db, 0x80000001), "2147483648 is a key, not a negative number"
      assert_equal [0xfffffffe, 3], lookup_v4(db, 0xffffffff), "4294967295 is a valid key, not an overflow"
    end

    def test_two_ipv6_keys_that_differ_after_byte_eight_order_unsigned
      low  = "0000000000000000" + "0000000000000001"
      high = "0000000000000000" + "ffffffffffffffff"
      db = build_database([record(6, low, low, ISP.merge("asn" => 11)),
                           record(6, high, high, ISP.merge("asn" => 22))])

      # A truncated int64 comparison would see both keys as 0 and order them
      # by luck; the blob compare orders them by their last eight bytes.
      assert_equal [[low, 11], [high, 22]], python_json(<<~PY, db)
        rows = [(r[0].hex(), r[2]) for r in conn.execute("SELECT * FROM v6 ORDER BY start")]
        print(json.dumps(rows))
      PY
      assert_equal 22, lookup_v6(db, high)&.last
    end

    def test_a_predecessor_that_ends_before_the_query_is_not_a_hit
      db = build_database([record(4, "01000000", "01000004", ISP.merge("asn" => 7)),
                           record(4, "01000010", "01000014", ISP.merge("asn" => 8))])

      assert_nil lookup_v4(db, 0x01000005), "the gap after a row must not return that row"
      assert_nil lookup_v4(db, 0x0100000f)
      assert_equal 8, lookup_v4(db, 0x01000010)&.last
    end

    def test_lookups_before_the_first_row_after_the_last_and_on_a_one_address_row
      db = build_database([record(4, "01000000", "01000000", ISP.merge("asn" => 9)),
                           record(4, "02000000", "02000004", ISP.merge("asn" => 10))])

      assert_nil lookup_v4(db, 0x00ffffff), "nothing precedes the first row"
      assert_nil lookup_v4(db, 0x02000005), "nothing follows the last row"
      assert_equal 9, lookup_v4(db, 0x01000000)&.last, "a single-address interval is still an interval"
    end

    # --- S03 ------------------------------------------------------------

    def test_a_packed_ipv6_key_matches_as_a_blob_and_never_as_text
      key = "20010db8" + "0" * 24
      db = build_database([record(6, key, key, ISP.merge("asn" => 42))])

      got = python_json(<<~PY, db)
        packed = bytes.fromhex("#{key}")
        sql = ("SELECT asn FROM (SELECT * FROM v6 WHERE start <= :ip ORDER BY start DESC LIMIT 1) "
               "AS candidate WHERE end >= :ip")
        blob = conn.execute(sql, {"ip": packed}).fetchone()
        text = conn.execute(sql, {"ip": packed.decode("latin-1")}).fetchone()
        print(json.dumps({"blob": blob and blob[0], "text": text and text[0]}))
      PY

      assert_equal 42, got["blob"], "the BLOB binding is the supported route"
      assert_nil got["text"], "the same bytes bound as TEXT must not match; SQLite never compares across types"
    end

    # --- S06 ------------------------------------------------------------

    def test_the_ddl_rejects_bad_booleans_wrong_key_widths_and_inverted_bounds
      db = build_database([record(4, "01000000", "01000004", ISP)])
      row = "2,3,1,'x','isp','stub',%s,0,0,0,0,0,0,0,'residential_isp','[]'"

      rejected = python_json(<<~PY, db, readonly: false)
        cases = {
          "boolean_two": "INSERT INTO v4 VALUES (#{format(row, '2')})",
          "boolean_text": "INSERT INTO v4 VALUES (#{format(row, "'x'")})",
          "inverted": "INSERT INTO v4 VALUES (9,8,1,'x','isp','stub',0,0,0,0,0,0,0,0,'residential_isp','[]')",
          "short_blob": ("INSERT INTO v6 VALUES (X'0001', X'0002', 1, 'x', 'isp', 'stub',"
                         " 0,0,0,0,0,0,0,0,'residential_isp','[]')"),
          "text_key": ("INSERT INTO v6 VALUES ('0000000000000000', '0000000000000001', 1, 'x', 'isp',"
                       " 'stub', 0,0,0,0,0,0,0,0,'residential_isp','[]')"),
          "flag_without_asn": ("INSERT INTO v4 VALUES (40,41,NULL,NULL,NULL,NULL,1,0,0,0,0,0,0,0,"
                               "'hosting','[]')"),
          "unknown_verdict": "INSERT INTO v4 VALUES (50,51,1,'x','isp','stub',0,0,0,0,0,0,0,0,'residential','[]')",
        }
        out = {}
        for label, sql in cases.items():
            try:
                conn.execute(sql)
                out[label] = None
            except sqlite3.IntegrityError as exc:
                out[label] = "rejected"
        print(json.dumps(out))
      PY

      rejected.each { |label, result| assert_equal "rejected", result, "#{label} must be rejected by the DDL" }
    end

    # --- S07 ------------------------------------------------------------

    def test_verify_fails_loudly_on_a_corrupt_source_list_and_an_unsupported_profile
      records = [record(4, "01000000", "01000004", ISP)]
      db = build_database(records)

      # core_sources that is not a JSON array of strings.
      broken = File.join(@dir, "broken.jsonl")
      File.write(broken, JSON.generate(records[0].merge("core_sources" => "asn_category")) + "\n")
      error = assert_raises(StageFailure) do
        Export::Sqlite.verify(database: db, records: broken, metadata: metadata_path)
      end
      assert_match(/core_sources/, error.message)

      # Metadata naming a profile this schema does not implement: the value
      # differs from what is stored, so verify refuses the pair.
      other = File.join(@dir, "profile.json")
      File.write(other, JSON.generate(JSON.parse(File.read(metadata_path))
                                          .merge("classification_profile" => "core-v2")))
      error = assert_raises(StageFailure) do
        Export::Sqlite.verify(database: db, records: File.join(@dir, "records.jsonl"), metadata: other)
      end
      assert_match(/classification_profile/, error.message)
    end

    # --- the cross-format gate itself -----------------------------------

    def test_the_validator_accepts_a_matching_pair_and_rejects_a_tampered_csv
      records = [record(4, "01000000", "01000004", ISP),
                 record(4, "01000010", "01000014", ISP.merge("asn" => 200, "as_org" => "Access B")),
                 record(6, "20010db8" + "0" * 24, "20010db8" + "f" * 24, BLANK)]
      db = build_database(records)
      csv = write_csv(records, name: "openasn.csv", reuse: true)
      csv_gz = Export::Gzip.compress(csv, output: "#{csv}.gz")
      sqlite_gz = Export::Gzip.compress(db, output: "#{db}.gz")

      report = Export::Validate.call(records: File.join(@dir, "records.jsonl"), metadata: metadata_path,
                                     csv: csv, csv_gz: csv_gz.path, sqlite: db, sqlite_gz: sqlite_gz.path)
      assert_equal 3, report.dig("checks", "csv", "total")
      assert_equal 2, report.dig("checks", "sqlite", "rows", "v4")

      tampered = File.join(@dir, "tampered.csv")
      File.write(tampered, File.read(csv).sub("Access B", "Access C"))
      error = assert_raises(StageFailure) do
        Export::Validate.call(records: File.join(@dir, "records.jsonl"), metadata: metadata_path, csv: tampered)
      end
      assert_match(/as_org/, error.message)
    end

    def test_the_writer_refuses_a_spool_whose_intervals_are_unordered
      overlapping = [record(4, "01000000", "01000004", ISP), record(4, "01000004", "01000008", ISP)]
      error = assert_raises(StageFailure) do
        Csv.write(write_spool(overlapping), path: File.join(@dir, "openasn.csv"))
      end
      assert_match(/unordered or overlapping/, error.message)
    end

    def test_the_validator_catches_an_overlap_and_a_missed_coalescing
      # Written past the writer's own ordering guard on purpose: the point
      # is that the GATE catches a bad file, whoever produced it.
      overlapping = [record(4, "01000000", "01000004", ISP), record(4, "01000004", "01000008", ISP)]
      error = assert_raises(StageFailure) { validate_handwritten(overlapping) }
      assert_match(/overlaps/, error.message)

      # Adjacent, identical payload: legal CSV, failed projection.
      uncoalesced = [record(4, "01000000", "01000004", ISP), record(4, "01000005", "01000008", ISP)]
      error = assert_raises(StageFailure) { validate_handwritten(uncoalesced) }
      assert_match(/coalesce/, error.message)
    end

    def test_a_truncated_gzip_is_rejected_rather_than_silently_short
      csv = write_csv([record(4, "01000000", "01000004", ISP)])
      gz = Export::Gzip.compress(csv, output: File.join(@dir, "openasn.csv.gz"))
      truncated = File.join(@dir, "truncated.gz")
      File.binwrite(truncated, File.binread(gz.path)[0..-4])

      assert_raises(StageFailure, Zlib::GzipFile::Error) do
        Export::Validate.validate_gzip(truncated, raw: csv)
      end
    end

    # --- metadata encodings ---------------------------------------------

    def test_metadata_values_are_text_with_the_documented_encodings
      meta = JSON.parse(File.read(metadata_path))

      assert_equal Export::Metadata::REQUIRED_KEYS.sort, meta.keys.sort
      meta.each_value { |value| assert_kind_of String, value }
      assert_equal "1", meta["schema_version"]
      assert_equal "0", meta["schema_revision"]
      assert_equal "core-v1", meta["classification_profile"]
      assert_equal "false", meta["tier_b_included"]
      assert_equal "tier_a", meta["scope"]
      assert_equal "CC0-1.0", meta["license"]
      # Compact JSON, keys sorted lexically, nothing pretty about it.
      assert_equal '{"base":1,"dc":0,"relay":0,"vpn":0}', JSON.parse(meta["input_layer_counts"])["ipv4"].then { |h| JSON.generate(h) }
      assert_equal meta["build_id"], meta["built_at"]
      refute_includes meta.keys, "sha256", "no output hash may appear inside the metadata it is embedded in"
    end

    def test_metadata_rejects_a_quoted_integer_and_a_non_canonical_json_value
      meta = JSON.parse(File.read(metadata_path))

      error = assert_raises(StageFailure) { Export::Metadata.validate!(meta.merge("records_total" => "007")) }
      assert_match(/base-10 integer/, error.message)

      error = assert_raises(StageFailure) { Export::Metadata.validate!(meta.merge("producer" => '{"b":1,"a":2}')) }
      assert_match(/canonical JSON/, error.message)

      error = assert_raises(StageFailure) { Export::Metadata.validate!(meta.merge("tier_b_included" => "0")) }
      assert_match(/true\/false/, error.message)
    end

    # --- helpers ---------------------------------------------------------

    # One spool object. `payload` overrides BLANK, so a case states only the
    # evidence it is about.
    def record(version, start_hex, end_hex, payload)
      BLANK.merge("ip_version" => version, "start_hex" => start_hex, "end_hex" => end_hex).merge(payload)
    end

    def write_spool(records, name: "records.jsonl")
      path = File.join(@dir, name)
      File.write(path, records.map { |r| JSON.generate(ordered(r)) + "\n" }.join)
      path
    end

    # The spool's fixed key order, which the writers rely on for nothing but
    # which the fixture should nonetheless respect.
    def ordered(record)
      Contract::SPOOL_FIELDS.to_h { |field| [field.to_s, record.fetch(field.to_s)] }
    end

    def write_csv(records, name: "openasn.csv", reuse: false)
      spool = reuse && File.exist?(File.join(@dir, "records.jsonl")) ? File.join(@dir, "records.jsonl")
                                                                     : write_spool(records)
      Csv.write(spool, path: File.join(@dir, name)).path
    end

    # Renders the CSV field by field without the writer's ordering guard, so
    # a deliberately broken file can reach the validator.
    def validate_handwritten(records)
      spool = write_spool(records)
      csv = File.join(@dir, "openasn.csv")
      File.write(csv, "#{Contract::CSV_HEADER}\n" + records.map { |r| Csv.line_for(ordered(r)) }.join)
      meta = JSON.parse(File.read(metadata_path))
      meta["records_ipv4"] = records.count { |r| r["ip_version"] == 4 }.to_s
      meta["records_ipv6"] = records.count { |r| r["ip_version"] == 6 }.to_s
      Export::Validate.validate_csv(csv, records: spool, meta: meta)
    end

    # A metadata file with every mandatory key, hand-built so the tests do
    # not need a data repo or a git checkout.
    def metadata_path
      @metadata_path ||= begin
        path = File.join(@dir, "metadata.json")
        File.write(path, JSON.pretty_generate(sample_metadata))
        path
      end
    end

    def sample_metadata
      {
        "attribution" => "Sources: synthetic fixture.\n",
        "build_id" => "2026-09-18T08:14:36Z",
        "build_unix_ts" => "1789719276",
        "built_at" => "2026-09-18T08:14:36Z",
        "classification_profile" => "core-v1",
        "data_repo_commit" => "0" * 40,
        "edition" => "core",
        "exporter_version" => "1.0.0",
        "input_artifacts" => '[{"bytes":10,"name":"openasn-ipv4.bin","sha256":"aa"}]',
        "input_layer_counts" => '{"ipv4":{"base":1,"dc":0,"relay":0,"vpn":0},' \
                                '"ipv6":{"base":1,"dc":0,"relay":0,"vpn":0}}',
        "license" => "CC0-1.0",
        "lookup_policy_version" => "1",
        "pipeline_repo_commit" => "1" * 40,
        "producer" => '{"go":null,"python":"3.9.6","ruby":"3.4.2","sqlite":"3.43.2"}',
        "records_ipv4" => "2",
        "records_ipv6" => "1",
        "records_total" => "3",
        "schema_revision" => "0",
        "schema_version" => "1",
        "scope" => "tier_a",
        "source_format_version" => "1",
        "sources" => '[{"id":"sapics-origin-asn","license":"PDDL-1.0"}]',
        "tier_b_included" => "false",
        "working_tree_dirty" => "true"
      }
    end

    # Builds a real database through sqlite.py, with metadata whose counts
    # match the records (verify cross-checks them).
    def build_database(records)
      spool = write_spool(records)
      meta = sample_metadata.merge(
        "records_ipv4" => records.count { |r| r["ip_version"] == 4 }.to_s,
        "records_ipv6" => records.count { |r| r["ip_version"] == 6 }.to_s,
        "records_total" => records.length.to_s
      )
      File.write(File.join(@dir, "metadata.json"), JSON.pretty_generate(meta))
      @metadata_path = File.join(@dir, "metadata.json")

      output = File.join(@dir, "openasn.sqlite")
      Export::Sqlite.build(records: spool, metadata: @metadata_path, output: output)
      output
    end

    # Runs a snippet against the finished database with the same interpreter
    # that wrote it, and parses its JSON. Keeps sqlite.py's CLI to the two
    # modes the PRD defines while still letting a test ask SQLite directly.
    def python_json(body, database, readonly: true)
      script = File.join(@dir, "probe-#{Digest::SHA256.hexdigest(body)[0, 8]}.py")
      open_call = readonly ? %(sqlite3.connect("file:" + sys.argv[1] + "?mode=ro", uri=True)) \
                           : %(sqlite3.connect(sys.argv[1]))
      File.write(script, "import json, sqlite3, sys\nconn = #{open_call}\n#{body}")
      stdout, stderr, status = Open3.capture3(Export::Sqlite.interpreter.command, script, database)
      flunk("probe failed: #{stderr}") unless status.success?
      JSON.parse(stdout)
    end

    LOOKUP = <<~PY
      sql = ("SELECT * FROM (SELECT * FROM {table} WHERE start <= :ip ORDER BY start DESC LIMIT 1) "
             "AS candidate WHERE end >= :ip")
    PY

    def lookup_v4(database, address)
      got = python_json(<<~PY, database)
        #{LOOKUP.sub('{table}', 'v4')}
        row = conn.execute(sql, {"ip": #{address}}).fetchone()
        print(json.dumps(None if row is None else [row[0], row[2]]))
      PY
      got
    end

    def lookup_v6(database, hex_key)
      python_json(<<~PY, database)
        #{LOOKUP.sub('{table}', 'v6')}
        row = conn.execute(sql, {"ip": bytes.fromhex("#{hex_key}")}).fetchone()
        print(json.dumps(None if row is None else [row[0].hex(), row[2]]))
      PY
    end
  end
end
