# frozen_string_literal: true

# The offline CI harness for the portable exports (PRD §17.1): a complete
# release, start to finish, from bytes this file makes up.
#
# It exists because every other export test proves one layer. The unit
# suites prove the projection and the writers against hand-authored
# fixtures; `exports:mmdb_test` proves the Go tool; `exports:from_release`
# proves the refusals. Nothing proved that the whole chain - native bytes
# in, three formats out, asset registry, manifest, checksums, and an OLD
# native client still finding its own three files in that manifest - works
# on one set of inputs in one run. That is the job here.
#
# Three properties are load-bearing and are the reason this is a fixture
# generator rather than a downloader:
#
#   * NO NETWORK, NO DATA REPO, NO SECRETS. The inputs are synthesized, the
#     source catalogue is a literal, and the export contract is the injected
#     fixture beside this file. A CI job that needed a release to exist
#     could not run on the PR that introduces the format.
#   * NOTHING CAN PUBLISH. The generation goes through Export::FromRelease,
#     which records `unknown` revisions and a dirty tree, drops a
#     NOT-PUBLISHABLE marker, and refuses to run at all under PUBLISH=1.
#     A synthetic release that could be mistaken for a real one would be a
#     far worse defect than the missing coverage this closes.
#   * THE TIMESTAMP IS FIXED. build_id is derived from the OASN header, so
#     a synthetic input with a frozen build_ts makes the entire output
#     deterministic - which is what lets the reproducibility check compare
#     payload hashes across two runs instead of comparing prose.
#
# The fixture is small (22 effective intervals) and deliberately awkward:
# a non-CIDR base range, overlays that split base ranges and overlays that
# cover no base range at all, an ASN with no org name, org names carrying a
# comma, a double quote and non-ASCII bytes, every category and every
# network role, and IPv6 outside the two prefixes the MMDB gate rejects.
# A fixture that only held tidy /24s would pass through a writer that had
# forgotten how to quote.

require "digest"
require "fileutils"
require "ipaddr"
require "json"
require "time"

require_relative "../lib/env"
require_relative "../lib/binary"
require_relative "../lib/orgs"
require_relative "../lib/release_assets"
require_relative "../export/contract"
require_relative "../export/from_release"
require_relative "../export/run"
require_relative "../export/spool"
require_relative "../export/mode"
require_relative "../publish"

module OpenASNPipeline
  module Tools
    module ExportCI
      # Frozen, and never Time.now: the build identity of the synthetic
      # release is a property of the fixture, not of the day CI ran.
      # 1_789_000_000 = 2026-09-10T00:26:40Z.
      BUILD_TS = 1_789_000_000
      BUILD_ID = Time.at(BUILD_TS).utc.iso8601

      RELEASE_DIR   = "release"
      EXPORT_DIR    = "export"
      CANDIDATE_DIR = "candidate"

      # The injected export contract (PRD §17.4). required_mode is `all`
      # here so the harness cannot silently degrade to producing nothing.
      CONTRACT_PATH = File.expand_path("../../test/fixtures/export-v1/export-contract-ci.json", __dir__)

      ATTRIBUTION = <<~TEXT
        # Attribution (synthetic CI fixture)

        These bytes are generated by pipeline/tools/export_ci.rb for offline
        validation. They describe no real network and must never be published.
      TEXT

      # A source catalogue shaped like a real one. FromRelease carries it
      # through verbatim rather than reconstructing it, which is exactly the
      # behavior under test: an export describes the fetches of the snapshot
      # it was built from.
      SOURCES = [
        { "id" => "synthetic-ci-fixture", "url" => "https://example.invalid/openasn-ci",
          "license" => "CC0-1.0", "license_sha256" => "cf" * 32,
          "fetched_at" => "2026-09-09T00:00:00Z" }
      ].freeze

      # A file no released manifest carries today. It is registered as an
      # ordinary payload so the old-client check has something additive and
      # genuinely unknown to ignore, which is the case PRD §17.1 names
      # ("additive unknown files") and the one a future asset will really be.
      UNKNOWN_ASSET = "openasn-future-signals.bin"

      CATEGORY_CODE = Export::Contract::CATEGORY_BY_CODE.invert.freeze
      ROLE_CODE     = Export::Contract::ROLE_BY_CODE.invert.freeze

      # AS64504 is deliberately absent: a routed range whose ASN has no org
      # name must export a NULL as_org rather than an empty string.
      ORG_NAMES = {
        64_496 => 'Example ISP, S.L. "Fibra"',
        64_497 => "Örebro Stadsnät AB",
        64_498 => "Example Hosting & CDN",
        64_499 => "Example Enterprise GmbH",
        64_500 => "Universidad de Ejemplo",
        64_501 => "Ministerio de Ejemplo",
        64_502 => "Example Mobile Networks",
        64_503 => "Example Bulletproof Hosting",
        64_505 => "Example Uncategorized Network",
        64_506 => "Example Business Park SA"
      }.freeze

      module_function

      # ---------------------------------------------------------------
      # the synthetic snapshot

      def flags(category: nil, role: nil, **signals)
        value = CATEGORY_CODE.fetch(category) | (ROLE_CODE.fetch(role) << Binary::ROLE_SHIFT)
        signals.each do |name, on|
          value |= Export::Contract::ASN_SIGNAL_BITS.fetch(name) if on
        end
        value
      end

      def ip(text) = IPAddr.new(text).to_i

      # [start, end, asn, flags], ascending and disjoint. Every category and
      # every network role in the core-v1 vocabulary appears at least once,
      # so the CSV and SQLite column round-trips see the whole alphabet.
      def ipv4_base
        [
          # Not a CIDR block: 201 addresses. The MMDB writer has to split it.
          [ip("100.64.0.0"), ip("100.64.0.200"), 64_503,
           flags(category: "hosting", role: "stub", bad_asn: true, hosting_extra: true)],
          [ip("192.0.2.0"), ip("192.0.2.127"), 64_496,
           flags(category: "isp", role: "access_provider")],
          [ip("192.0.2.128"), ip("192.0.2.255"), 64_497,
           flags(category: "isp", role: "tier1_transit")],
          # AS64504 has no entry in the org sidecar.
          [ip("192.88.99.0"), ip("192.88.99.255"), 64_504,
           flags(category: "isp", role: "access_provider")],
          [ip("198.51.100.0"), ip("198.51.100.255"), 64_498,
           flags(category: "hosting", role: "content_network", cdn: true)],
          [ip("203.0.113.0"), ip("203.0.113.63"), 64_499,
           flags(category: "business", role: "stub", enterprise_gw: true)],
          [ip("203.0.113.64"), ip("203.0.113.127"), 64_500,
           flags(category: "education_research", role: "midsize_transit")],
          [ip("203.0.113.128"), ip("203.0.113.191"), 64_501,
           flags(category: "government_admin", role: "major_transit")],
          [ip("203.0.113.192"), ip("203.0.113.255"), 64_502,
           flags(category: "isp", role: "access_provider", mobile_carrier: true)],
          # No category and no role: the `unknown` verdict with asn_no_category.
          [ip("203.0.114.0"), ip("203.0.114.255"), 64_505, flags],
          # Business WITHOUT the enterprise-gateway signal, which is the only
          # way the plain `business` verdict is reachable: enterprise_gateway
          # is scoped to SWG/SASE evidence, not to the category.
          [ip("203.0.115.0"), ip("203.0.115.255"), 64_506,
           flags(category: "business", role: "stub")]
        ]
      end

      # Overlay a: straddles two base rows, so the sweep splits both.
      # Overlay b: covers no base row at all, so it exports as an unrouted
      # interval that still carries its overlay evidence.
      def ipv4_vpn
        [[ip("192.0.2.64"), ip("192.0.2.191")],
         [ip("198.18.0.0"), ip("198.18.0.255")]]
      end

      def ipv4_dc
        [[ip("198.19.0.0"), ip("198.19.0.255")],
         [ip("198.51.100.128"), ip("198.51.100.255")]]
      end

      # Every range is outside ::/96 and ::ffff:0:0/96, which PRD §12.4
      # gates: a native IPv6 row inside either would fail MMDB generation,
      # and a fixture that tripped the gate would test the gate instead of
      # the pipeline.
      def ipv6_base
        [
          [ip("2001:db8::"), ip("2001:db8::ffff"), 64_496,
           flags(category: "isp", role: "access_provider")],
          [ip("2001:db8:1::"), ip("2001:db8:1::ffff"), 64_498,
           flags(category: "hosting", role: "content_network", cdn: true)],
          [ip("2001:db8:2::"), ip("2001:db8:2::ffff"), 64_502,
           flags(category: "isp", role: "access_provider", mobile_carrier: true)],
          [ip("2606:4700::"), ip("2606:4700::ffff"), 64_499,
           flags(category: "business", role: "stub", enterprise_gw: true)]
        ]
      end

      # Runs off the end of the first base row and into the gap beyond it,
      # so one exported interval is overlay-only IPv6.
      def ipv6_vpn = [[ip("2001:db8::8000"), ip("2001:db8::1:7fff")]]
      def ipv6_dc  = [[ip("2606:4700::"), ip("2606:4700::7fff")]]

      # Writes the synthetic release directory: the three native artifacts,
      # the attribution the exports embed, and a manifest that describes
      # them. Written through the PRODUCTION writers (Binary.write,
      # Orgs.write) on purpose - a fixture that hand-packed its own headers
      # could keep passing after the real writer changed layout.
      def write_release(dir)
        FileUtils.mkdir_p(dir)
        v4 = File.join(dir, "openasn-ipv4.bin")
        v6 = File.join(dir, "openasn-ipv6.bin")
        orgs = File.join(dir, "openasn-orgs.bin")

        Binary.write(v4, family: :ipv4, build_ts: BUILD_TS, base_rows: ipv4_base,
                         vpn_rows: ipv4_vpn, dc_rows: ipv4_dc)
        Binary.write(v6, family: :ipv6, build_ts: BUILD_TS, base_rows: ipv6_base,
                         vpn_rows: ipv6_vpn, dc_rows: ipv6_dc)
        Orgs.write(orgs, ORG_NAMES.to_h { |asn, name| [asn, { "name" => name }] })
        File.write(File.join(dir, "ATTRIBUTION.md"), ATTRIBUTION)

        write_release_manifest(dir)
        Env.log("export CI: synthetic release #{BUILD_ID} written to #{dir} " \
                "(#{ipv4_base.length} v4 base rows, #{ipv6_base.length} v6 base rows, " \
                "#{ORG_NAMES.size} org names)")
        dir
      end

      # FromRelease verifies every input against this manifest before it
      # reads a byte of it, so the digests here are measured from the files
      # that were just written rather than asserted.
      def write_release_manifest(dir)
        files = %w[openasn-ipv4.bin openasn-ipv6.bin openasn-orgs.bin ATTRIBUTION.md].map do |name|
          path = File.join(dir, name)
          { "name" => name, "sha256" => Digest::SHA256.file(path).hexdigest,
            "bytes" => File.size(path), "records" => 0 }
        end
        File.write(File.join(dir, "manifest.json"), JSON.pretty_generate(
          "format_version" => FORMAT_VERSION, "edition" => Export::Contract::EDITION,
          "build_id" => BUILD_ID, "files" => files, "sources" => SOURCES
        ) + "\n")
      end

      # ---------------------------------------------------------------
      # the candidate a release would be assembled from

      def mode(selected: ENV[Export::Mode::ENV_NAME])
        Export::Mode.resolve(selected: selected, config_path: CONTRACT_PATH, publishing: false)
      end

      # Turns a finished export staging directory plus the synthetic natives
      # into the thing a publisher would see: an explicit inventory, a
      # manifest, and SHA256SUMS. Then re-reads all three from disk and
      # proves the promises PRD §15.2/§15.3 make about them.
      #
      # Everything here goes through the production ReleaseAssets/Publish
      # code. A harness that assembled its own manifest would be validating
      # the harness.
      def assemble(release:, export:, candidate:, resolved: mode)
        Env.fail_stage!("#{candidate} already exists; the harness assembles a fresh candidate") if File.exist?(candidate)
        FileUtils.mkdir_p(candidate)

        registry = ReleaseAssets.new(root: candidate)
        natives = adopt_natives(registry, release: release, candidate: candidate)
        # An asset from a build newer than any client that exists today.
        File.binwrite(File.join(candidate, UNKNOWN_ASSET), "OFUT\x01future evidence".b)
        registry.register(name: UNKNOWN_ASSET, path: File.join(candidate, UNKNOWN_ASSET), records: 0)

        exports = export_descriptors(export)
        Publish.adopt_exports(registry, exports, dir: candidate)
        registry.require_exports!(resolved.assets)

        manifest = Publish.manifest_document(
          build_id: BUILD_ID, registry: registry, sources: SOURCES,
          stats: { synthetic: true, mode: resolved.selected },
          export_producer: export_producer(resolved, export)
        )
        Publish.write_manifest(manifest, dir: candidate)
        registry.envelope(name: "SHA256SUMS", path: Publish.write_sha256sums(registry, dir: candidate))
        registry.envelope(name: "manifest.json", path: File.join(candidate, "manifest.json"))
        registry.verify!

        report = check_candidate!(candidate, registry: registry, natives: natives, resolved: resolved,
                                  export: export)
        Env.log("export CI: candidate #{BUILD_ID} assembled and checked in #{candidate} " \
                "(#{registry.payload_names.join(', ')})")
        report
      end

      # Copies the native inputs into the candidate rather than moving them:
      # the synthetic release directory is the harness's own evidence of
      # what was fed in, and a later run diffing a failure needs it intact.
      def adopt_natives(registry, release:, candidate:)
        counts = {}
        Publish::NATIVE_ARTIFACTS.each do |name|
          source = File.join(release, name)
          FileUtils.cp(source, File.join(candidate, name))
          records = if name == "openasn-orgs.bin"
                      File.binread(source, 16)[8, 4].unpack1("N")
                    else
                      Binary::Artifact.new(source).counts[:base]
                    end
          counts[name] = records
          registry.register(name: name, path: File.join(candidate, name), records: records)
        end
        FileUtils.cp(File.join(release, "ATTRIBUTION.md"), File.join(candidate, "ATTRIBUTION.md"))
        registry.register(name: "ATTRIBUTION.md", path: File.join(candidate, "ATTRIBUTION.md"), records: 0)
        counts
      end

      # Rebuilds the export descriptors from the staging directory that
      # `exports:from_release` left behind, so the assembly step can run as
      # its own rake task against a directory rather than only inside one
      # long-lived process.
      Exports = Struct.new(:outputs, :metadata_path, keyword_init: true)

      def export_descriptors(export)
        metadata_path = File.join(export, Export::Run::METADATA_NAME)
        unless File.file?(metadata_path)
          Env.fail_stage!("#{export} holds no #{Export::Run::METADATA_NAME}: run exports:from_release first")
        end
        meta = JSON.parse(File.read(metadata_path))
        counts = Export::Spool::Counts.new(ipv4: Integer(meta.fetch("records_ipv4")),
                                           ipv6: Integer(meta.fetch("records_ipv6")),
                                           bytes: 0, sha256: nil)

        outputs = SPEC.filter_map do |name, spec|
          path = File.join(export, name)
          next nil unless File.file?(path)

          raw = spec[:raw] && File.join(export, spec[:raw])
          uncompressed = if raw
                           { "name" => spec[:raw], "bytes" => File.size(raw),
                             "sha256" => Digest::SHA256.file(raw).hexdigest }
                         end
          Export::Run::Descriptor.new(
            name: name, path: path, bytes: File.size(path),
            sha256: Digest::SHA256.file(path).hexdigest, records: counts.total,
            export: Export::Run.export_block(counts: counts, format: spec[:format],
                                             media_type: spec[:media_type],
                                             content_encoding: spec[:content_encoding],
                                             uncompressed: uncompressed)
          )
        end
        Exports.new(outputs: outputs, metadata_path: metadata_path)
      end

      # Mirrors the data repo's export-contract.json `asset_formats`. Kept
      # as data rather than as three near-identical branches so that a new
      # asset is one line here and one line in the contract.
      SPEC = {
        "openasn.csv.gz" => { format: "csv", media_type: "text/csv; charset=utf-8",
                              content_encoding: "gzip", raw: "openasn.csv" },
        "openasn.sqlite.gz" => { format: "sqlite", media_type: "application/vnd.sqlite3",
                                 content_encoding: "gzip", raw: "openasn.sqlite" },
        "openasn.mmdb" => { format: "mmdb", media_type: "application/octet-stream",
                            content_encoding: "identity", raw: nil }
      }.freeze

      def export_producer(resolved, export)
        meta = JSON.parse(File.read(File.join(export, Export::Run::METADATA_NAME)))
        {
          exporter_version: Export::Contract::EXPORTER_VERSION, mode: resolved.selected,
          schema_version: Export::Contract::SCHEMA_VERSION, schema_revision: Export::Contract::SCHEMA_REVISION,
          classification_profile: Export::Contract::CLASSIFICATION_PROFILE,
          lookup_policy_version: Export::Contract::LOOKUP_POLICY_VERSION,
          data_repo_commit: meta.fetch("data_repo_commit"),
          pipeline_repo_commit: meta.fetch("pipeline_repo_commit"),
          working_tree_dirty: meta.fetch("working_tree_dirty") == "true",
          tools: JSON.parse(meta.fetch("producer"))
        }
      end

      # ---------------------------------------------------------------
      # what the assembled candidate has to be true about

      def check_candidate!(candidate, registry:, natives:, resolved:, export:)
        check_vocabulary!(File.join(export, "openasn.csv"))
        manifest = JSON.parse(File.read(File.join(candidate, "manifest.json")))
        entries = manifest.fetch("files")

        check_manifest_entries!(candidate, entries)
        check_envelopes_absent!(entries)
        check_export_entries!(entries, resolved: resolved)
        check_old_native_client!(manifest, natives: natives)
        check_checksums!(candidate, registry: registry)

        { "build_id" => BUILD_ID, "mode" => resolved.selected, "candidate" => candidate,
          "payloads" => registry.payloads.to_h { |asset| [asset.name, asset.sha256] },
          "envelopes" => %w[SHA256SUMS manifest.json].to_h { |name| [name, registry[name].sha256] },
          "records" => entries.to_h { |entry| [entry.fetch("name"), entry.fetch("records")] } }
      end

      # The fixture has to be WORTH running: if an edit here quietly dropped
      # the last row carrying some verdict, every writer would still agree
      # with every other writer about a narrower dataset and CI would stay
      # green. So the emitted CSV is read back and required to exercise the
      # whole core-v1 vocabulary, plus the three text shapes that are easy to
      # get wrong: a field needing quotes, a non-ASCII field, a NULL org.
      def check_vocabulary!(csv_path)
        require "csv"
        Env.fail_stage!("#{csv_path} is missing; nothing to check the vocabulary against") unless File.file?(csv_path)
        rows = ::CSV.read(csv_path, headers: true, encoding: "UTF-8")

        {
          "core_verdict" => Export::Contract::VERDICTS,
          "category" => Export::Contract::CATEGORIES,
          "network_role" => Export::Contract::NETWORK_ROLES
        }.each do |column, vocabulary|
          seen = rows.filter_map { |row| row[column] }.uniq
          missing = vocabulary - seen
          unless missing.empty?
            Env.fail_stage!("the synthetic fixture emits no #{column} #{missing.join(', ')}; every core-v1 " \
                            "#{column} has to appear or the round-trip proves nothing about it")
          end
          unknown = seen - vocabulary
          Env.fail_stage!("#{column} carries #{unknown.inspect}, outside core-v1") unless unknown.empty?
        end

        text = File.read(csv_path, encoding: "UTF-8")
        Env.fail_stage!("no quoted CSV field: the fixture stopped exercising quoting") unless text.include?('""')
        Env.fail_stage!("no non-ASCII org name in the fixture") if text.ascii_only?
        unless rows.any? { |row| row["asn"] && row["as_org"].nil? }
          Env.fail_stage!("no routed row with a NULL as_org: an ASN with no org name must still export")
        end
        unless rows.any? { |row| row["asn"].nil? }
          Env.fail_stage!("no unrouted row: an overlay covering no base range must still export")
        end
        Env.log("export CI: the fixture exercises every core-v1 verdict, category and network role " \
                "across #{rows.length} intervals")
      end

      # Every entry describes the file that is actually on disk beside it.
      def check_manifest_entries!(candidate, entries)
        entries.each do |entry|
          name = entry.fetch("name")
          path = File.join(candidate, name)
          Env.fail_stage!("manifest names #{name}, which is not in the candidate") unless File.file?(path)

          bytes = File.size(path)
          sha = Digest::SHA256.file(path).hexdigest
          next if bytes == entry.fetch("bytes") && sha == entry.fetch("sha256")

          Env.fail_stage!("manifest says #{name} is #{entry['bytes']} bytes/#{entry['sha256']}, " \
                          "the candidate holds #{bytes} bytes/#{sha}")
        end
      end

      # A file cannot honestly carry its own hash, so neither envelope may
      # appear in the list the envelopes describe (PRD §15.2).
      def check_envelopes_absent!(entries)
        named = entries.map { |entry| entry.fetch("name") }
        ReleaseAssets::ENVELOPE_NAMES.each do |envelope|
          next unless named.include?(envelope)

          Env.fail_stage!("manifest.files lists #{envelope}; the envelopes describe the payloads and are " \
                          "never among them")
        end
      end

      # The export identity travels NESTED under `export`, never as new
      # top-level manifest keys - that nesting is the whole reason an old
      # native client can read this manifest at all (PRD §15.3).
      def check_export_entries!(entries, resolved:)
        exported = entries.select { |entry| entry.key?("export") }.to_h { |e| [e.fetch("name"), e] }
        unless exported.keys.sort == resolved.assets.sort
          Env.fail_stage!("manifest carries export blocks for #{exported.keys.sort.inspect}, " \
                          "mode #{resolved.selected} declares #{resolved.assets.sort.inspect}")
        end

        exported.each do |name, entry|
          block = entry.fetch("export")
          expected = {
            "schema_version" => Export::Contract::SCHEMA_VERSION,
            "schema_revision" => Export::Contract::SCHEMA_REVISION,
            "classification_profile" => Export::Contract::CLASSIFICATION_PROFILE,
            "lookup_policy_version" => Export::Contract::LOOKUP_POLICY_VERSION,
            "scope" => Export::Contract::SCOPE, "tier_b_included" => Export::Contract::TIER_B_INCLUDED,
            "format" => SPEC.fetch(name)[:format],
            "media_type" => SPEC.fetch(name)[:media_type],
            "content_encoding" => SPEC.fetch(name)[:content_encoding]
          }
          expected.each do |key, want|
            next if block[key] == want

            Env.fail_stage!("#{name} export block #{key} is #{block[key].inspect}, expected #{want.inspect}")
          end
          # MMDB is read through an mmap, so the bytes the manifest names
          # ARE the bytes a reader opens: no decoded twin to describe.
          if SPEC.fetch(name)[:raw].nil?
            Env.fail_stage!("#{name} carries an uncompressed block") if block.key?("uncompressed")
          elsif block.dig("uncompressed", "name") != SPEC.fetch(name)[:raw]
            Env.fail_stage!("#{name} does not describe its decoded twin #{SPEC.fetch(name)[:raw]}")
          end
        end
      end

      # PRD §15.3 / test id U22, against a REAL assembled manifest rather
      # than a fixture: a client that predates the exports resolves its
      # three artifacts and is untouched by everything added since.
      def check_old_native_client!(manifest, natives:)
        view = Publish.native_client_view(manifest)
        names = view.map { |entry| entry["name"] || entry[:name] }
        unless names == Publish::NATIVE_ARTIFACTS
          Env.fail_stage!("an old native client resolves #{names.inspect} from this manifest, " \
                          "expected #{Publish::NATIVE_ARTIFACTS.inspect}")
        end

        view.each do |entry|
          name = entry["name"] || entry[:name]
          if entry.key?("export") || entry.key?(:export)
            Env.fail_stage!("#{name} carries an export block; the native artifacts must stay plain entries")
          end
          records = entry["records"] || entry[:records]
          next if records == natives.fetch(name)

          Env.fail_stage!("#{name} reports #{records.inspect} records to a native client, " \
                          "the artifact holds #{natives.fetch(name)}")
        end

        ignored = manifest.fetch("files").map { |entry| entry.fetch("name") } - Publish::NATIVE_ARTIFACTS
        Env.log("export CI: an old native client resolves #{names.join(', ')} and ignores the " \
                "#{ignored.length} entries it has no name for (#{ignored.join(', ')})")
      end

      # SHA256SUMS: `sha256sum -c` format, filename order, self-excluding,
      # and every line true of the file on disk.
      def check_checksums!(candidate, registry:)
        lines = File.read(File.join(candidate, "SHA256SUMS")).lines(chomp: true)
        names = lines.map { |line| line.split("  ", 2).last }
        unless names == names.sort
          Env.fail_stage!("SHA256SUMS is not in file-name order: #{names.inspect}")
        end
        unless names.sort == registry.payload_names.sort
          Env.fail_stage!("SHA256SUMS covers #{names.sort.inspect}, the inventory holds " \
                          "#{registry.payload_names.sort.inspect}")
        end

        lines.each do |line|
          sha, name = line.split("  ", 2)
          actual = Digest::SHA256.file(File.join(candidate, name)).hexdigest
          next if actual == sha

          Env.fail_stage!("SHA256SUMS claims #{name} hashes to #{sha}, it hashes to #{actual}")
        end
      end

      # ---------------------------------------------------------------
      # one whole generation, for the reproducibility check

      # Synthetic inputs -> exports -> assembled candidate, in a directory
      # of its own. Returns the report, whose payload hashes are the thing
      # two generations are compared on.
      def generation(root:, resolved: mode)
        FileUtils.mkdir_p(root)
        release = File.join(root, RELEASE_DIR)
        export = File.join(root, EXPORT_DIR)
        candidate = File.join(root, CANDIDATE_DIR)

        write_release(release)
        Export::FromRelease.call(input: release, output: export, mode: resolved.selected)
        assemble(release: release, export: export, candidate: candidate, resolved: resolved)
      end

      # PRD §17.1: the same synthetic input bytes and the same fixed
      # timestamp, twice, compared on every payload hash.
      #
      # WHAT IS AND IS NOT CLAIMED. Byte identity is asserted only WITHIN
      # this recorded producer environment - one Ruby, one zlib, one Python
      # and its SQLite library, one Go toolchain - because that is the only
      # scope in which it is true: a different SQLite library writes a
      # physically different (equally valid) database, and a different zlib
      # deflates differently. So the toolchain is printed with the verdict,
      # and nothing here asserts that another runner would produce these
      # same hashes.
      def reproduce(root:, resolved: mode)
        first  = generation(root: File.join(root, "generation-1"), resolved: resolved)
        second = generation(root: File.join(root, "generation-2"), resolved: resolved)

        stamped = JSON.parse(JSON.parse(File.read(File.join(root, "generation-1", EXPORT_DIR,
                                                            Export::Run::METADATA_NAME))).fetch("producer"))
        # The embedded producer must describe every tool this mode used.
        # Repeatable bytes with missing tool provenance are not sufficient.
        effective = Export::Run.producer(mode: resolved.selected)
        missing = effective.reject { |key, value| value.nil? || stamped[key] == value }
        unless missing.empty?
          Env.fail_stage!("export CI: the reproduced metadata records #{missing.keys.join(', ')} as " \
                   "#{missing.keys.map { |k| stamped[k].inspect }.join(', ')} although this mode used " \
                   "#{missing.values.map(&:inspect).join(', ')}. Producer metadata must match the tools used.")
        end
        differing = (first["payloads"].keys | second["payloads"].keys).reject do |name|
          first["payloads"][name] == second["payloads"][name]
        end
        unless differing.empty?
          detail = differing.map { |n| "#{n}: #{first['payloads'][n]} vs #{second['payloads'][n]}" }
          Env.fail_stage!("two generations of the same synthetic input at the same fixed timestamp " \
                          "produced different bytes under one producer environment " \
                          "(#{effective.merge(stamped) { |_k, a, b| a || b }}):\n  " \
                          "#{detail.join("\n  ")}")
        end
        unless first["envelopes"] == second["envelopes"]
          Env.fail_stage!("the payloads reproduced but the envelopes did not: " \
                          "#{first['envelopes'].inspect} vs #{second['envelopes'].inspect}")
        end

        Env.log("export CI: #{first['payloads'].size} payloads and both envelopes reproduced " \
                "byte-for-byte across two generations")
        { "build_id" => BUILD_ID, "mode" => resolved.selected, "reproduced" => true,
          "scope" => "byte identity is claimed only within this recorded producer environment",
          "producer" => effective, "metadata_producer" => stamped,
          "payloads" => first["payloads"], "envelopes" => first["envelopes"] }
      end
    end
  end
end
